### ISSUE TITLE
Missing sounds: There are no exclusive sound effects!

### ISSUE THREAD

**Issue by Blunder-G** [dainxt/DungeonsMod-Issue-Tracker#28]
I hurted a Crawler!

Crawler: ...

I killed a King!

King: ...

I beated the Void Master!

Void Master: ...

There are no special sounds that creatures that they can perform or no sounds for damage. THIS IS A VERY BIG PROBLEM

**Comment by dainxt** [comment]
Your issue made me laugh of sadness. Not because is a bug, is because there's no a lot exclusive sounds yet 😢. Anyway, I really would like to add exclusive sounds, I'm planning to add such effects but for me would take time to do sound engineering. So anyone that read this and would like apport sounds to the project, let me know...

**Comment by dainxt** [comment]
Soon™

**Comment by Blunder-G** [comment]
> Soon™

What? One of my favorite boss and mob mod gonna take an update for unique sounds... I'll wait that with my all curiositys!
